#!/usr/bin/env bash
# Configure a server to listen at port 80.
sudo sed -i 's/listen 8080/listen 80/' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen [::]:8080/listen [::]:80/' /etc/nginx/sites-enabled/default
sudo service nginx restart
