#!/usr/bin/env bash
# Script that creates a file, kills the process and display messages
sudo bash -c 'echo $$ > /var/run/holbertonscript.pid'
trap 'sudo rm -f /var/run/holbertonscript.pid; echo "I hate the kill command"; exit' SIGTERM
trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'sudo rm -f /var/run/holbertonscript.pid; exit' SIGQUIT
while true
do
    echo "To infinity and beyond"
done
