#!/usr/bin/env bash
# Script that creates a file, kills the process and display messages
sudo bash -c 'echo $$ > /var/run/holbertonscript.pid'
trap 'echo "I hate the kill command"; sudo rm -f /var/run/holbertonscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'sudo rm -f /var/run/holbertonscript.pid; exit' SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
