#!/usr/bin/env bash
# This Script displays To infinity and beyond indefinitely, With a sleep 2 in between each iteration and display I am invincible!!! when receiving a SIGTERM signal.
n=1
while [ $n -gt 0 ]
do
    echo "To infinity and beyond"
    sleep 2
    trap "echo I am invincible!!!" SIGTERM
done
