#!/usr/bin/env bash
#  Script that displays numbers from 1 to 100 with fizz buzz conditionals
for (( n=1; n<=100; n++ ))
do
    if [ $((n%15)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((n%3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((n%5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$n"
    fi
done
