#!/usr/bin/env bash
# Script to configure container to fit the requirements.
pkill -f apache2
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
chmod 007 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
